name: Tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test:
    name: Run rust tests and compiler suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang gcc-aarch64-linux-gnu python3 python3-pip cargo

      - name: Run Rust unit tests
        run: cargo test --verbose

      - name: Run custom test suits
        run: python3 run_tests.py --arch-style=gnu
        env:
          GITHUB_ANNOTATIONS: "1"
