name: Tests
on: [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test:
    name: Run rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo test --verbose